

![1562417614315](C:\Users\Michael.NPALT035\AppData\Roaming\Typora\typora-user-images\1562417614315.png)

To test if the input into the get_greeting function would print I first imported the get_greeting function from the file app.py

![1562417776272](C:\Users\Michael.NPALT035\AppData\Roaming\Typora\typora-user-images\1562417776272.png)

I then created the test_get_greeting asserting that 'Hello' + 'test_name' + ', Welcome to the Tour' was the expected outcome.

![1562417697749](C:\Users\Michael.NPALT035\AppData\Roaming\Typora\typora-user-images\1562417697749.png)



![1562417847070](C:\Users\Michael.NPALT035\AppData\Roaming\Typora\typora-user-images\1562417847070.png)

To test if the input into the get_greeting function would print I first imported the day_break from the file app.py

![1562417729503](C:\Users\Michael.NPALT035\AppData\Roaming\Typora\typora-user-images\1562417729503.png)

I then created the test_day_break expecting it the break because I used an integer outside the range 1-31

![1562418044719](C:\Users\Michael.NPALT035\AppData\Roaming\Typora\typora-user-images\1562418044719.png)

â€‹	

test_day_notbreak was created to expected to return the integer 30, because it is within the range 1-31

![1562418117120](C:\Users\Michael.NPALT035\AppData\Roaming\Typora\typora-user-images\1562418117120.png)



